/*
 * generated by Xtext
 */
package com.thesoftwarefactory.vertx.web.mvc;

import org.eclipse.xtext.generator.IGenerator;

import com.thesoftwarefactory.vertx.web.mvc.generator.CodegenDslGenerator;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CodegenDslRuntimeModule extends com.thesoftwarefactory.vertx.web.mvc.AbstractCodegenDslRuntimeModule {

	@Override
	public Class<? extends IGenerator> bindIGenerator() {
		return CodegenDslGenerator.class;
	}
	
}
