/*
 * generated by Xtext
 */
package com.thesoftwarefactory.vertx.web.mvc.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CodegenDslUiModule extends com.thesoftwarefactory.vertx.web.mvc.ui.AbstractCodegenDslUiModule {
	public CodegenDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
