/*
 * generated by Xtext
 */
package com.thesoftwarefactory.vertx.web.mvc.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.thesoftwarefactory.vertx.web.mvc.services.CodegenDslGrammarAccess;

public class CodegenDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private CodegenDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.thesoftwarefactory.vertx.web.mvc.parser.antlr.internal.InternalCodegenDslParser createParser(XtextTokenStream stream) {
		return new com.thesoftwarefactory.vertx.web.mvc.parser.antlr.internal.InternalCodegenDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public CodegenDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CodegenDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
