/*
 * generated by Xtext
 */
package com.thesoftwarefactory.vertx.web.mvc.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.thesoftwarefactory.vertx.web.mvc.ui.internal.CodegenDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CodegenDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CodegenDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CodegenDslActivator.getInstance().getInjector(CodegenDslActivator.COM_THESOFTWAREFACTORY_VERTX_WEB_MVC_CODEGENDSL);
	}
	
}
