/**
 * generated by Xtext
 */
package com.thesoftwarefactory.vertx.web.mvc.validation;

import com.thesoftwarefactory.vertx.web.mvc.validation.AbstractCodegenDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class CodegenDslValidator extends AbstractCodegenDslValidator {
}
