/**
 * generated by Xtext
 */
package com.thesoftwarefactory.vertx.web.mvc.ui.labeling;

import org.eclipse.xtext.xbase.ui.labeling.XbaseDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class CodegenDslDescriptionLabelProvider extends XbaseDescriptionLabelProvider {
}
