/**
 * generated by Xtext
 */
package com.thesoftwarefactory.vertx.web.mvc.ui.contentassist;

import com.thesoftwarefactory.vertx.web.mvc.ui.contentassist.AbstractCodegenDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class CodegenDslProposalProvider extends AbstractCodegenDslProposalProvider {
}
